version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "/r2sqs-eb/sonar_token"
    SONAR_HOST_URL: "/r2sqs-eb/sonar_host_url"

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "INSTALL sonar-scanner"
      - export SONAR_SCANNER_VERSION=6.2.1.4610
      - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux-x64.zip
      - unzip -q sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux-x64.zip
      - export SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-${SONAR_SCANNER_VERSION}-linux-x64

  pre_build:
    commands:
      - echo "Starting Redis locally"
      - (which redis-server && redis-server --daemonize yes) || docker run -d -p 6379:6379 redis:alpine || echo "Redis start failed, but continuing..."
      - echo "Installing dependencies and running tests for coverage"
      - cd customer && npm install && npm test && cd ..
      - cd products && npm install && npm test && cd ..
      - cd shopping && npm install && npm test && cd ..

  build:
    commands:
      - echo "Running SonarQube analysis"
      - echo "Sonar host -> $SONAR_HOST_URL"
      - $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.projectKey=r2sqs-eb -Dsonar.projectName="r2sqs-eb Microservices" -Dsonar.sources=customer/src,products/src,shopping/src -Dsonar.exclusions=**/node_modules/**,**/*.test.js -Dsonar.javascript.lcov.reportPaths=customer/coverage/lcov.info,products/coverage/lcov.info,shopping/coverage/lcov.info -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN -Dsonar.qualitygate.wait=true